from __future__ import annotations

from protolink.core.models import FeatureModule, ModuleStatus


def build_module_catalog() -> list[FeatureModule]:
    return [
        FeatureModule(
            key="dashboard",
            name="工作台总览",
            area="基础底座",
            milestone="M0",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="统一工作台入口，负责展示工作区状态、模块导航、当前能力分布和交付基线。",
            acceptance=(
                "应用可以稳定启动并进入主工作台。",
                "工作区会自动初始化且状态可见。",
                "模块导航、模块说明和功能入口保持一致。",
            ),
        ),
        FeatureModule(
            key="serial_studio",
            name="串口工作台",
            area="传输链路",
            milestone="M1",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="统一串口生命周期、收发控制、原始字节留痕与预设管理。",
            acceptance=(
                "可以枚举并打开串口。",
                "收发日志保留原始字节。",
                "连接异常不会冻结界面。",
            ),
        ),
        FeatureModule(
            key="modbus_rtu_lab",
            name="Modbus RTU 调试台",
            area="协议调试",
            milestone="M2",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="面向 Modbus RTU 的完整工作流入口，覆盖报文组装、串口发送、寄存器监视与报文分析联动。",
            acceptance=(
                "RTU 报文组装与解析对同一原始字节达成一致。",
                "请求可以通过已连接的 RTU 传输链路发送。",
                "寄存器监视与报文分析始终保持同一链路上下文。",
            ),
        ),
        FeatureModule(
            key="modbus_tcp_lab",
            name="Modbus TCP 调试台",
            area="协议调试",
            milestone="M2",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="面向 Modbus TCP 的完整工作流入口，覆盖请求组装、TCP 发送、寄存器监视与报文分析联动。",
            acceptance=(
                "TCP 请求组装与解析输出对同一负载达成一致。",
                "请求可以通过已连接的 TCP 客户端发送。",
                "寄存器监视与报文分析保持同一路径闭环。",
            ),
        ),
        FeatureModule(
            key="mqtt_client",
            name="MQTT 客户端",
            area="传输链路",
            milestone="M1",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="Broker 连接、订阅发布、负载格式转换与报文分析共享链路。",
            acceptance=(
                "客户端可以连接、订阅与发布。",
                "负载格式转换明确且可重复。",
            ),
        ),
        FeatureModule(
            key="mqtt_server",
            name="MQTT 服务端",
            area="传输链路",
            milestone="M1",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="本地 Broker 模式，覆盖启动停止、消息发布、认证配置与报文留痕。",
            acceptance=(
                "服务端可以稳定启动和停止。",
                "认证与消息日志可以独立配置。",
            ),
        ),
        FeatureModule(
            key="tcp_client",
            name="TCP 客户端",
            area="传输链路",
            milestone="M1",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="原始套接字客户端工作面，覆盖会话生命周期、发送控制与共享报文分析。",
            acceptance=(
                "客户端生命周期与其他传输面保持一致。",
                "接收负载可以被查看与导出。",
            ),
        ),
        FeatureModule(
            key="tcp_server",
            name="TCP 服务端",
            area="传输链路",
            milestone="M1",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="本地监听服务端工作面，覆盖监听管理、客户端统计、广播发送与共享报文分析。",
            acceptance=(
                "服务端可以安全承载多个会话。",
                "单会话可见性与广播行为保持明确。",
            ),
        ),
        FeatureModule(
            key="udp_lab",
            name="UDP 工作台",
            area="传输链路",
            milestone="M1",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="无连接报文收发工作面，覆盖绑定、远端目标控制与共享报文分析。",
            acceptance=(
                "绑定与发送行为可以分离控制。",
                "收发负载会保留在日志中。",
            ),
        ),
        FeatureModule(
            key="packet_inspector",
            name="报文分析台",
            area="共享能力",
            milestone="M2",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="统一报文分析台，提供原始负载视图、字节优先组包与基于事件总线的日志汇聚。",
            acceptance=(
                "所有传输模块都能写入同一个报文分析模型。",
                "解析失败后仍保留原始字节。",
                "原始报文草稿可以按字节优先方式组装和预览。",
                "选中报文行可以输出基础 Modbus RTU/TCP 解码结果。",
                "回放计划可从分析台装载并分发到活动传输会话。",
                "可见报文可导出为回放计划文件用于迭代调试。",
            ),
        ),
        FeatureModule(
            key="register_monitor",
            name="寄存器监视",
            area="共享能力",
            milestone="M2",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="面向寄存器类协议和设备模板的复用监视面，包含点位模型、字节序和解码能力。",
            acceptance=(
                "寄存器元数据可以导入和导出。",
                "字节序和缩放规则清晰可见。",
            ),
        ),
        FeatureModule(
            key="automation_rules",
            name="自动化规则",
            area="自动化",
            milestone="M3",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="跨传输的规则匹配、转换与响应流水线，具备运行期安全控制和基础管理面板。",
            acceptance=(
                "规则可以安全启动和停止。",
                "规则命中过程可见且可审计。",
                "自动化运行时的停止与禁用边界保持明确。",
            ),
        ),
        FeatureModule(
            key="script_console",
            name="脚本控制台",
            area="自动化",
            milestone="M3",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="基于受限脚本宿主的工作区脚本执行面，提供输出、错误和脚本证据留存。",
            acceptance=(
                "脚本在受控宿主中运行。",
                "日志与失败证据绑定到同一工作区。",
            ),
        ),
        FeatureModule(
            key="data_tools",
            name="数据工具",
            area="共享能力",
            milestone="M2",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="提供确定性的编码、校验、格式转换与 JSON 辅助工具，不依赖传输链路状态。",
            acceptance=(
                "工具可独立于传输状态打开。",
                "转换结果可预测且有测试覆盖。",
            ),
        ),
        FeatureModule(
            key="network_tools",
            name="网络诊断",
            area="运维诊断",
            milestone="M4",
            status=ModuleStatus.BOOTSTRAPPED,
            summary="面向 Windows 的只读优先网络诊断面，强调非写入边界和连通性验证。",
            acceptance=(
                "高权限操作边界清晰可见。",
                "每条变更路径都包含确认和回退指引。",
            ),
        ),
    ]
